App/visitor/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, BooleanField
from wtforms.fields.html5 import DateField, IntegerField

from ..utils.utils import get_animal_type_choices, get_exhibit_choices


class SearchExhibitForm(FlaskForm):
    name = StringField('Name')

    # still need to set constraint that min < max
    min_animal = IntegerField('Min Number of Animals')
    max_animal = IntegerField('Max Number of Animals')

    min_size = IntegerField('Minimum Size')
    max_size = IntegerField('Maximum Size')

    water = SelectField('Water', choices=[('', ''), (1, 'yes'), (0, 'no')])
    sort_by = SelectField('Order By', choices=[('True', ''), ('NAME', 'Name'),
                                              ('WATER', 'Water'), ('SIZE', 'Size'),
                                              ('C', 'Number of Animals')])

    direction = BooleanField('Descending')

    search = SubmitField('Search')


class SearchAnimalForm(FlaskForm):
    name = StringField('Name')
    species = StringField('Species')

    exhibit = SelectField('Exhibit', choices=get_exhibit_choices())

    # still need to set constraint that min < max
    min_age = IntegerField('Minimum Age')
    max_age = IntegerField('Maximum Age')

    type = SelectField('Type', choices=get_animal_type_choices())
    sort_by = SelectField('Order By', choices=[('True', ''), ('NAME', 'Name'),
                                              ('SPECIES', 'Species'), ('EXHIBIT', 'Exhibit'),
                                              ('AGE', 'Age'), ('TYPE', 'Type')])

    direction = BooleanField('Descending')

    search = SubmitField('Search')

    @classmethod
    def new(cls):
        # Instantiate the form
        form = cls()

        # Update the choices for the agency field
        form.exhibit.choices = get_exhibit_choices()
        form.type.choices = get_animal_type_choices()
        return form


class SearchShowForm(FlaskForm):
    name = StringField('Name')
    date = DateField('Date')

    exhibit = SelectField('Exhibit', choices=get_exhibit_choices())

    sort_by = SelectField('Order By', choices=[('True', ''), ('NAME', 'Name'),
                                              ('EXHIBIT', 'Exhibit'), ('DATE_TIME', 'Date')])
    direction = BooleanField('Descending')

    search = SubmitField('Search')

    @classmethod
    def new(cls):
        # Instantiate the form
        form = cls()

        # Update the choices for the agency field
        form.exhibit.choices = get_exhibit_choices()
        return form


class ViewExhibitHistoryForm(FlaskForm):
    name = StringField('Name')

    # still need to set constraint that min < max
    min_visits = IntegerField('Min Number of Visits')
    max_visits = IntegerField('Max Number of Visits')

    date = DateField('Date')
    sort_by = SelectField('Order By', choices=[('True', ''), ('NAME', 'Name'),
                                              ('WATER', 'Water'), ('SIZE', 'Size'),
                                              ('C', 'Number of Animals')])

    direction = BooleanField('Descending')

    search = SubmitField('Search')


class ViewShowHistoryForm(FlaskForm):
    name = StringField('Name')

    exhibit = SelectField('Exhibit', choices=get_exhibit_choices())
    date = DateField('Date')

    sort_by = SelectField('Order By', choices=[('True', ''), ('NAME', 'Name'),
                                              ('EXHIBIT', 'Exhibit'), ('DATE_TIME', 'Date')])
    direction = BooleanField('Descending')

    search = SubmitField('Search')

    @classmethod
    def new(cls):
        # Instantiate the form
        form = cls()

        # Update the choices for the agency field
        form.exhibit.choices = get_exhibit_choices()
        return form


class ExhibitDetail(FlaskForm):
    search = SubmitField('Log visit')

App/visitor/__init__.py
from flask import Blueprint

bp = Blueprint('visitor', __name__)

from . import views

App/visitor/views.py
from flask import render_template, flash, redirect, url_for
from datetime import datetime as dt

from . import bp
from .forms import ViewShowHistoryForm, ViewExhibitHistoryForm, SearchShowForm, SearchAnimalForm, SearchExhibitForm, \
    ExhibitDetail
from ..__init__ import db
from ..utils.utils import login_required
from flask_login import current_user
import pymysql

WATER = {0: 'No', 1: 'Yes'}


@bp.route('/')
@login_required("VISITOR")
def visitor():
    return render_template('visitor/visitor.html')


@bp.route('/search_exhibit', methods=['GET', 'POST'])
@login_required("VISITOR")
def search_exhibit():
    form = SearchExhibitForm()

    min_animal = form.min_animal.data
    max_animal = form.max_animal.data

    if min_animal and min_animal < 0:
        flash("Min must be positive", 'warning')
        return redirect(url_for("visitor.search_exhibit"))

    if max_animal and max_animal < 0:
        flash("Max must be positive", 'warning')
        return redirect(url_for("visitor.search_exhibit"))

    if (min_animal and max_animal) and max_animal < min_animal:
        flash("Max must be more than Min", 'warning')
        return redirect(url_for("visitor.search_exhibit"))

    min_size = form.min_size.data
    max_size = form.max_size.data

    if min_size and min_size < 0:
        flash("Min must be positive", 'warning')
        return redirect(url_for("visitor.search_exhibit"))

    if max_size and max_size < 0:
        flash("Max must be positive", 'warning')
        return redirect(url_for("visitor.search_exhibit"))

    if (min_size and max_size) and max_size < min_size:
        flash("Max must be more than Min", 'warning')
        return redirect(url_for("visitor.search_exhibit"))

    sort_by = form.sort_by.data if form.sort_by.data != "None" else "True"
    direction = "ASC" if form.direction.data is False else "DESC"
    sql = f"SELECT * FROM (SELECT " \
          f"EXHIBIT.NAME, EXHIBIT.SIZE, EXHIBIT.WATER, COUNT(*) AS C FROM EXHIBIT LEFT JOIN ANIMAL ON (EXHIBIT.NAME = ANIMAL.EXHIBIT) WHERE " \
          f"(EXHIBIT.NAME = '{form.name.data}' or '{form.name.data}' = '') AND " \
          f"(EXHIBIT.SIZE >= '{form.min_size.data}' or '{form.min_size.data}' = 'None') AND " \
          f"(EXHIBIT.SIZE <= '{form.max_size.data}' or '{form.max_size.data}' = 'None') AND " \
          f"(EXHIBIT.WATER =  '{form.water.data}' or '{form.water.data}' = '')" \
          f"GROUP BY EXHIBIT.NAME) AS T " \
          f"WHERE (C >= '{form.min_animal.data}' or '{form.min_animal.data}' = 'None') AND " \
          f"(C <= '{form.max_animal.data}' or '{form.max_animal.data}' = 'None') ORDER BY {sort_by} {direction}"

    result = db.query(sql).fetchall()
    items = [{'Name': result[i][0], 'Size': result[i][1], 'Water': WATER[result[i][2]], 'Number of Animals': result[i][3], 'Link': 'exhibit_detail/'+result[i][0]} for i in
             range(len(result))]

    return render_template('visitor/search_exhibit.html', form=form, items=items, title='Search Exhibit')


@bp.route('/view_exhibit_history', methods=['GET', 'POST'])
@login_required("VISITOR")
def view_exhibit_history():
    form = ViewExhibitHistoryForm()

    min_visits = form.min_visits.data
    max_visits = form.max_visits.data

    if min_visits and min_visits < 0:
        flash("Min must be positive", 'warning')
        return redirect(url_for("visitor.view_exhibit_history"))

    if max_visits and max_visits < 0:
        flash("Max must be positive", 'warning')
        return redirect(url_for("visitor.view_exhibit_history"))

    if (min_visits and max_visits) and max_visits < min_visits:
        flash("Max must be more than Min", 'warning')
        return redirect(url_for("visitor.view_exhibit_history"))

    username = current_user.username
    sort_by = form.sort_by.data if form.sort_by.data != "None" else "True"
    direction = "ASC" if form.direction.data is False else "DESC"
    sql = f"SELECT A.EXHIBIT, DATE_TIME, C FROM (SELECT EXHIBIT, DATE_TIME FROM VISIT_EXHIBIT WHERE VISITOR='{username}') AS A" \
          f" LEFT JOIN " \
          f"(SELECT EXHIBIT, COUNT(*) AS C FROM VISIT_EXHIBIT WHERE VISITOR='{username}' GROUP BY EXHIBIT) AS B " \
          f"ON (A.EXHIBIT=B.EXHIBIT) WHERE" \
          f"(A.EXHIBIT = '{form.name.data}' or '{form.name.data}' = '') AND " \
          f"(A.DATE_TIME = '{form.date.data}' or '{form.date.data}' = 'None') AND " \
          f"(C <= '{form.max_visits.data}' or '{form.max_visits.data}' = 'None') AND " \
          f"(C >= '{form.min_visits.data}' or '{form.min_visits.data}' = 'None') ORDER BY {sort_by} {direction}"

    result = db.query(sql).fetchall()
    items = [{'Name': result[i][0], 'Time': result[i][1], 'Number of Visits': result[i][2], 'Link':'exhibit_detail/'+result[i][0]} for i in range(len(result))]

    return render_template('visitor/view_exhibit_history.html', form=form, items=items, title='View Exhibit History')


@bp.route('/search_show', methods=['GET', 'POST'])
@login_required("VISITOR")
def search_show():
    form = SearchShowForm.new()
    sort_by = form.sort_by.data if form.sort_by.data != "None" else "True"
    direction = "ASC" if form.direction.data is False else "DESC"
    sql = f"SELECT NAME, DATE_TIME, EXHIBIT FROM `SHOW` WHERE " \
          f"(NAME = '{form.name.data}' or '{form.name.data}' = '') AND " \
          f"(date(DATE_TIME) = '{form.date.data}' or '{form.date.data}' = 'None') AND " \
          f"(EXHIBIT = '{form.exhibit.data}' or '{form.exhibit.data}' = '') ORDER BY {sort_by} {direction}"
    result = db.query(sql).fetchall()
    items = [{'Name': result[i][0], 'Exhibit': result[i][2], 'Date': result[i][1],'Link': 'exhibit_detail/'+result[i][2], 'Log Visit':'log_show/'+result[i][0]+'/'+str(result[i][1])} for i in range(len(result))]

    return render_template('visitor/search_show.html', form=form, items=items, title='Search Show')


@bp.route('/log_show/<string:name>/<string:date>', methods=['GET', 'POST'])
@login_required("VISITOR")
def log_show(name, date):

    sql = f"SELECT * FROM VISIT_SHOW WHERE " \
          f"(VISITOR = '{current_user.username}') AND " \
          f"(DATE_TIME = '{date}')"

    if db.query(sql).fetchone():
        flash(f"You have another show at the same time", 'warning')
        return redirect(url_for('visitor.search_show'))

    if dt.now() >= dt.strptime(date, '%Y-%m-%d %H:%M:%S'):
        sql = f"SELECT EXHIBIT FROM `SHOW` WHERE NAME = '{name}'"
        result = db.query(sql).fetchone()
        sql = f"INSERT INTO VISIT_SHOW (SHOW_NAME, DATE_TIME, VISITOR) VALUES ('{name}', '{date}', '{current_user.username}')"
        r = db.query(sql)
        sql = f"INSERT INTO VISIT_EXHIBIT (EXHIBIT, DATE_TIME, VISITOR) VALUES('{result[0]}', '{date}', '{current_user.username}')"
        s = db.query(sql)
    else:
        flash('Show not happened yet', 'warning')
        return redirect(url_for('visitor.search_show'))

    if not isinstance(r, pymysql.cursors.Cursor):
        flash('Impossible to log you in', 'warning')
        return redirect(url_for('visitor.search_show'))

    if not isinstance(s, pymysql.cursors.Cursor):
        flash('Impossible to log you in the exhibit', 'warning')
        return redirect(url_for('visitor.search_show'))

    flash("You successfully logged the visit", 'success')

    return redirect(url_for('visitor.search_show'))


@bp.route('/view_show_history', methods=['GET', 'POST'])
@login_required("VISITOR")
def view_show_history():
    form = ViewShowHistoryForm.new()

    username = current_user.username
    sort_by = form.sort_by.data if form.sort_by.data != "None" else "True"
    direction = "ASC" if form.direction.data is False else "DESC"
    sql = f"SELECT A.SHOW_NAME, A.DATE_TIME, B.EXHIBIT FROM " \
          f"(SELECT SHOW_NAME, DATE_TIME FROM VISIT_SHOW WHERE VISITOR= '{username}') AS A " \
          f"LEFT JOIN " \
          f"(SELECT NAME, DATE_TIME, EXHIBIT FROM `SHOW`) AS B " \
          f"ON (A.SHOW_NAME= B.NAME AND A.DATE_TIME= B.DATE_TIME) WHERE" \
          f"(SHOW_NAME = '{form.name.data}' or '{form.name.data}' = '') AND " \
          f"(A.DATE_TIME =  '{form.date.data}' or '{form.date.data}' = 'None') ORDER BY {sort_by} {direction}"
    result = db.query(sql).fetchall()
    items = [{'Name': result[i][0], 'Time': result[i][1], 'Exhibit': result[i][2]} for i in range(len(result))]

    return render_template('visitor/view_show_history.html', form=form, items=items, title='View Show History')


@bp.route('/search_animal', methods=['GET', 'POST'])
@login_required("VISITOR")
def search_animal():
    form = SearchAnimalForm.new()

    min_age = form.min_age.data
    max_age = form.max_age.data

    if min_age and min_age < 0:
        flash("Min must be positive", 'warning')
        return redirect(url_for("visitor.search_animal"))

    if max_age and max_age < 0:
        flash("Max must be positive", 'warning')
        return redirect(url_for("visitor.search_animal"))

    if (min_age and max_age) and max_age < min_age:
        flash("Max must be more than Min", 'warning')
        return redirect(url_for("visitor.search_animal"))

    sort_by = form.sort_by.data if form.sort_by.data != "None" else "True"
    direction = "ASC" if form.direction.data is False else "DESC"
    sql = f"SELECT NAME, SPECIES, EXHIBIT, AGE, TYPE FROM ANIMAL WHERE " \
          f"(NAME = '{form.name.data}' or '{form.name.data}' = '') AND " \
          f"(SPECIES = '{form.species.data}' or '{form.species.data}' = '') AND " \
          f"(EXHIBIT = '{form.exhibit.data}' or '{form.exhibit.data}' = '') AND " \
          f"(AGE >= '{form.min_age.data}' or '{form.min_age.data}' = 'None') AND " \
          f"(AGE <= '{form.max_age.data}' or '{form.max_age.data}' = 'None') AND " \
          f"(TYPE =  '{form.type.data}' or '{form.type.data}' = '') ORDER BY {sort_by} {direction}"

    result = db.query(sql).fetchall()

    items = [{'Name': result[i][0], 'Species': result[i][1], 'Exhibit': result[i][2], 'Age': result[i][3],

App/templates/visitor/animal_detail.html
{% import 'bootstrap/wtf.html' as wtf %}

{% extends "layout.html" %}
{% include "search_form.html" %}
{% include "nav_bar.html" %}
{% block content %}

 <h1>
        Animal Details
 </h1>

{% include "table_temp.html" %}

{% endblock content %}

App/templates/visitor/exhibit_detail.html
<script src="https://www.w3schools.com/lib/w3.js"></script>
<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet" />
{% import 'bootstrap/wtf.html' as wtf %}
{% extends "layout.html" %}
{% include "search_form.html" %}
{% include "nav_bar.html" %}
{% block content %}

 <h1>
        Exhibit Details
 </h1>


<h2>More About the Exhibit</h2>
<table id="myTable">
   <tr>
       {% for k in items1[0] %}
            <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child({{ loop.index }})')"> {{ k }} </th>
       {% endfor %}
   </tr>
    {% for d in items1 %}
   <tr class = "item">
         {% for k in d %}
        <td>{{ d[k] }}</td>
         {% endfor %}
  </tr>
   {% endfor %}
 </table>


<div id="form" style = "text-align: center; margin-top: 5%; margin-bottom: 5%; margin-left: 45%; margin-right: 45%;">
    {{ wtf.quick_form(form, form_type="horizontal") }}
</div>

<h2>More About the Animals</h2>
<table id="myTable">
   <tr>
       {% for k in items2[0] %}
            <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child({{ loop.index }})')"> {{ k }} </th>
       {% endfor %}
   </tr>
    {% for d in items2 %}
   <tr class = "item">
         {% for k in d %}
             {% if k == 'Link' %}
                <td><a href = "{{ d[k] }}">Animal Details</a></td>
             {% else %}
                <td>{{ d[k] }}</td>
             {% endif %}
         {% endfor %}
  </tr>
   {% endfor %}
 </table>


 <style>
td, th {
  border: 1px solid #999;
  padding: 0.5rem;
  color: #111; font-family: 'Helvetica Neue', sans-serif;

}

th { border-style: solid; border-color: black; background: rgb(255,255,255); /* Old browsers */
background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(241,241,241,1) 50%, rgba(225,225,225,1) 51%, rgba(246,246,246,1) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#f6f6f6',GradientType=0 );}

table {width: 60%; margin-left:20%; margin-right:20%; margin-top: 5%; border-color: black;}

h2 {color: #111; font-family: 'Helvetica Neue', sans-serif; font-size: 20px;
    font-weight: bold; letter-spacing: -1px; line-height: 1; text-align: center; margin-top: 5%;}
</style>

{% endblock content %}

App/templates/visitor/search_animal.html
{% import 'bootstrap/wtf.html' as wtf %}
{% import 'bootstrap/wtf.html' as wtf %}

{% extends "layout.html" %}
{% include "search_form.html" %}
{% include "nav_bar.html" %}
{% block content %}

 <h1>
        Search for Animals
 </h1>

<div class="content-section" style="margin-left: 30%; margin-right: 30%; margin-top: 10%;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.species.label(class="form-control-label") }}
                    {% if form.species.errors %}
                        {{ form.species(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.species.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.species(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.min_age.label(class="form-control-label") }}
                    {% if form.min_age.errors %}
                        {{ form.min_age(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.min_age.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.min_age(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.max_age.label(class="form-control-label") }}
                    {% if form.max_age.errors %}
                        {{ form.max_age(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.max_age.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.max_age(class="form-control form-control-lg") }}
                    {% endif %}
                 </div>
                <div class="form-group">
                    {{ form.type.label(class="form-control-label") }}
                    {% if form.type.errors %}
                        {{ form.type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.exhibit.label(class="form-control-label") }}

                    {% if form.exhibit.errors %}
                        {{ form.exhibit(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.exhibit.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.exhibit(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.sort_by.label(class="form-control-label") }}
                    {% if form.sort_by.errors %}
                        {{ form.sort_by(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.sort_by.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.sort_by(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.direction.label(class="form-control-label") }}
                    {% if form.direction.errors %}
                        {{ form.direction(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.direction.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.direction(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.search(class="btn btn-outline-info") }}
            </div>
        </form>
 </div>

<table id="myTable">
   <tr>
       {% for k in items[0] %}
            <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child({{ loop.index }})')"> {{ k }} </th>
       {% endfor %}
   </tr>
    {% for d in items %}
   <tr class = "item">
         {% for k in d %}
             {% if k == 'Link' %}
                <td><a href="{{ d[k] }}">Exhibit Details</a></td>
             {% else %}
                <td>{{ d[k] }}</td>
             {% endif %}
         {% endfor %}
  </tr>
   {% endfor %}
 </table>

<style>
td, th {
  border: 1px solid #999;
  padding: 0.5rem;
  color: #111; font-family: 'Helvetica Neue', sans-serif;

}


th { border-style: solid; border-color: black; background: rgb(255,255,255); /* Old browsers */
background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(241,241,241,1) 50%, rgba(225,225,225,1) 51%, rgba(246,246,246,1) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#f6f6f6',GradientType=0 );}


table {width: 60%; margin-left:20%; margin-right:20%; margin-top: 5%; border-color: black; }
</style>

{% endblock content %}

App/templates/visitor/visitor.html
{% extends "layout.html" %}
{% include "nav_bar.html" %}
{% block content %}


<div style = "text-align: center; margin: 10%; padding: 5px; text-decoration: none;">
    <button type="button" class="btn btn-outline-primary waves-effect"><a href="{{ url_for('visitor.search_exhibit') }}" style="text-decoration: none; color: black;">Search Exhibits</a></button>

    <button type="button" class="btn btn-outline-primary waves-effect"><a href="{{ url_for('visitor.view_exhibit_history') }}" style="text-decoration: none; color: black;">View Exhibit History</a></button>

    <button type="button" class="btn btn-outline-primary waves-effect"><a href="{{ url_for('visitor.search_show') }}" style="text-decoration: none; color: black;">Search Shows</a></button>
</div>
<div style = "text-align: center;">
    <button type="button" class="btn btn-outline-primary waves-effect"><a href="{{ url_for('visitor.view_show_history') }}" style="text-decoration: none; color: black;">View Show History</a></button>

    <button type="button" class="btn btn-outline-primary waves-effect"><a href="{{ url_for('visitor.search_animal') }}" style="text-decoration: none; color: black;">Search for Animals</a></button>
</div>




{% endblock content %}