App/staff/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, BooleanField
from wtforms.fields.html5 import IntegerField

from wtforms.validators import DataRequired, length

from ..utils.utils import get_animal_type_choices, get_exhibit_choices


class SearchAnimalForm(FlaskForm):
    name = StringField('Name')
    species = StringField('Species')
    min_age = IntegerField('Minimum Age')
    max_age = IntegerField('Maximum Age')
    exhibit = SelectField('Exhibit', choices=get_exhibit_choices())
    type = SelectField('Type', choices=get_animal_type_choices())
    search = SubmitField('Search')

    sort_by = SelectField('Order By', choices=[('True', ''), ('NAME', 'Name'),
                                              ('SPECIES', 'Species'), ('EXHIBIT', 'Exhibit'),
                                              ('AGE', 'Age'), ('TYPE', 'Type')])

    direction = BooleanField('Descending')

    @classmethod
    def new(cls):
        # Instantiate the form
        form = cls()

        # Update the choices for the agency field
        form.exhibit.choices = get_exhibit_choices()
        form.type.choices = get_animal_type_choices()
        return form


class AnimalCareForm(FlaskForm):
    text = StringField('Text', validators=[DataRequired()])
    text = TextAreaField('Note', validators=[DataRequired(), length(max=200)], render_kw={"rows": 11, "cols": 50})
    submit = SubmitField('Log Note')

App/staff/__init__.py
from flask import Blueprint

bp = Blueprint('staff', __name__)

from . import views

App/staff/views.py
from datetime import datetime as dt

from flask import render_template, flash, redirect, url_for
from flask_login import current_user

from . import bp
from .forms import SearchAnimalForm, AnimalCareForm
from ..__init__ import db
from ..utils.utils import login_required


@bp.route('/')
@login_required("STAFF")
def staff():
    return render_template('staff/staff.html')


@bp.route('/search_animal',  methods=['GET', 'POST'])
@login_required("STAFF")
def search_animal():
    form = SearchAnimalForm.new()
    min_age = form.min_age.data
    max_age = form.max_age.data

    if min_age and min_age < 0:
        flash("Min must be positive", 'warning')
        return redirect(url_for("staff.search_animal"))

    if max_age and max_age < 0:
        flash("Max must be positive", 'warning')
        return redirect(url_for("staff.search_animal"))

    if (min_age and max_age) and max_age < min_age:
        flash("Max must be more than Min", 'warning')
        return redirect(url_for("staff.search_animal"))

    sort_by = form.sort_by.data if form.sort_by.data != "None" else "True"
    direction = "ASC" if form.direction.data is False else "DESC"
    sql = f"SELECT NAME, SPECIES, EXHIBIT, AGE, TYPE FROM ANIMAL WHERE " \
          f"(NAME = '{form.name.data}' or '{form.name.data}' = '') AND " \
          f"(SPECIES = '{form.species.data}' or '{form.species.data}' = '') AND " \
          f"(EXHIBIT = '{form.exhibit.data}' or '{form.exhibit.data}' = '') AND " \
          f"(AGE >= '{form.min_age.data}' or '{form.min_age.data}' = 'None') AND " \
          f"(AGE <= '{form.max_age.data}' or '{form.max_age.data}' = 'None') AND " \
          f"(TYPE =  '{form.type.data}' or '{form.type.data}' = '') ORDER BY {sort_by} {direction}"

    result = db.query(sql).fetchall()

    items = [{'Name': result[i][0], 'Species': result[i][1], 'Exhibit': result[i][2], 'Age': result[i][3],
              'Type': result[i][4], 'Link': 'search_animal/'+result[i][0]+'/'+result[i][1]} for i in range(len(result))]

    return render_template('staff/search_animal.html', form=form, items=items, title='Search Animal')



@bp.route('/view_shows')
@login_required("STAFF")
def view_shows():
    sql = f"SELECT NAME, DATE_TIME, EXHIBIT FROM `SHOW` WHERE HOST = '{current_user.username}'"

    result = db.query(sql).fetchall()

    items = [{'Name': result[i][0], 'Date': result[i][1], 'Exhibit': result[i][2]} for i in range(len(result))]

    return render_template('staff/view_shows.html', items=items, title='View Show')


@bp.route('/search_animal/<string:name>/<string:species>', methods=['GET', 'POST'])
@login_required("STAFF")
def animal_care(name, species):
    sql = f"SELECT NAME, SPECIES, EXHIBIT, AGE, TYPE FROM ANIMAL WHERE " \
          f"(NAME = '{name}') AND (SPECIES = '{species}')"

    result = db.query(sql).fetchall()
    items1 = [{'Name': result[i][0], 'Species': result[i][1], 'Exhibit': result[i][2], 'Age': result[i][3],
              'Type': result[i][4]} for i in range(len(result))]

    form = AnimalCareForm()

    if form.validate_on_submit():
        sql = f"INSERT INTO ANIMAL_CARE (ANIMAL, SPECIES, STAFF_MEMBER, DATE_TIME, NOTE)" \
              f"VALUES ('{name}', '{species}', '{current_user.username}', " \
              f"'{dt.now()}', '{form.text.data}')"

        db.query(sql)

        form.text.data = None

    sql = f"SELECT STAFF_MEMBER, NOTE, DATE_TIME FROM ANIMAL_CARE WHERE ANIMAL = '{name}'"

    result = db.query(sql).fetchall()
    items2 = [{'staff Member': result[i][0], 'Note': result[i][1], 'Time': result[i][2]} for i in range(len(result))]

    return render_template('staff/animal_care.html', items1=items1, items2=items2, form=form, title='Animal Care')

App/templates/staff/animal_care.html
<script src="https://www.w3schools.com/lib/w3.js"></script>
<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet" />
{% import 'bootstrap/wtf.html' as wtf %}
{% extends "layout.html" %}
{% include "search_form.html" %}
{% include "nav_bar.html" %}
{% block content %}

 <h1>
        Animal Care
 </h1>

<table id="myTable">
   <tr>
       {% for k in items1[0] %}
            <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child({{ loop.index }})')"> {{ k }} </th>
       {% endfor %}
   </tr>
    {% for d in items1 %}
   <tr class = "item">
         {% for k in d %}
        <td>{{ d[k] }}</td>
         {% endfor %}
  </tr>
   {% endfor %}
 </table>


<div class="content-section" style="margin-left: 30%; margin-right: 30%; margin-top: 10%;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.text.label(class="form-control-label") }}

                    {% if form.text.errors %}
                        {{ form.text(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.text.errors %}
                                <p class=error><strong>Error:</strong> {{ error }}
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.text(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
 </div>

<table id="myTable">
   <tr>
       {% for k in items2[0] %}
            <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child({{ loop.index }})')"> {{ k }} </th>
       {% endfor %}
   </tr>
    {% for d in items2 %}
   <tr class = "item">
         {% for k in d %}
        <td>{{ d[k] }}</td>
         {% endfor %}
  </tr>
   {% endfor %}
 </table>


 <style>
td, th {
  border: 1px solid #999;
  padding: 0.5rem;
  color: #111; font-family: 'Helvetica Neue', sans-serif;

}

th { border-style: solid; border-color: black; background: rgb(255,255,255); /* Old browsers */
background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(241,241,241,1) 50%, rgba(225,225,225,1) 51%, rgba(246,246,246,1) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#f6f6f6',GradientType=0 );}

table {width: 60%; margin-left:20%; margin-right:20%; margin-top: 5%; border-color: black;}
</style>

{% endblock content %}

App/templates/staff/search_animal.html
{% import 'bootstrap/wtf.html' as wtf %}

{% extends "layout.html" %}
{% include "search_form.html" %}
{% include "nav_bar.html" %}
{% block content %}



 <h1>
        Search Animal
 </h1>

<div class="content-section" style="margin-left: 30%; margin-right: 30%; margin-top: 10%;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <p class=error><strong>Error:</strong> {{ error }} </p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.species.label(class="form-control-label") }}
                    {% if form.species.errors %}
                        {{ form.species(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.species.errors %}
                               <p class=error><strong>Error:</strong> {{ error }} </p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.species(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.min_age.label(class="form-control-label") }}
                    {% if form.min_age.errors %}
                        {{ form.min_age(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.min_age.errors %}
                               <p class=error><strong>Error:</strong> {{ error }} </p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.min_age(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.max_age.label(class="form-control-label") }}
                    {% if form.max_age.errors %}
                        {{ form.max_age(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.max_age.errors %}
                                <p class=error><strong>Error:</strong> {{ error }} </p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.max_age(class="form-control form-control-lg") }}
                    {% endif %}
                 </div>
                <div class="form-group">
                    {{ form.type.label(class="form-control-label") }}
                    {% if form.type.errors %}
                        {{ form.type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.type.errors %}
                                <p class=error><strong>Error:</strong> {{ error }} </p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.exhibit.label(class="form-control-label") }}

                    {% if form.exhibit.errors %}
                        {{ form.exhibit(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.exhibit.errors %}
                                <p class=error><strong>Error:</strong> {{ error }} </p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.exhibit(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.sort_by.label(class="form-control-label") }}
                    {% if form.sort_by.errors %}
                        {{ form.sort_by(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.sort_by.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.sort_by(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.direction.label(class="form-control-label") }}
                    {% if form.direction.errors %}
                        {{ form.direction(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.direction.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.direction(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.search(class="btn btn-outline-info") }}
            </div>
        </form>
 </div>


<table id="myTable">
   <tr>
       {% for k in items[0] %}
            <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child({{ loop.index }})')"> {{ k }} </th>
       {% endfor %}
   </tr>
    {% for d in items %}
   <tr class = "item">
         {% for k in d %}
             {% if k == 'Link' %}
                <td><a href="{{ d[k] }}">Animal Care</a></td>
             {% else %}
                <td>{{ d[k] }}</td>
             {% endif %}
         {% endfor %}
  </tr>
   {% endfor %}
 </table>

<style>
td, th {
  border: 1px solid #999;
  padding: 0.5rem;
  color: #111; font-family: 'Helvetica Neue', sans-serif;

}


th { border-style: solid; border-color: black; background: rgb(255,255,255); /* Old browsers */
background: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(241,241,241,1) 50%, rgba(225,225,225,1) 51%, rgba(246,246,246,1) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, rgba(255,255,255,1) 0%,rgba(241,241,241,1) 50%,rgba(225,225,225,1) 51%,rgba(246,246,246,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#f6f6f6',GradientType=0 );}


table {width: 60%; margin-left:20%; margin-right:20%; margin-top: 5%; border-color: black; }
</style>


{% endblock content %}

App/templates/staff/staff.html
{% extends "layout.html" %}
{% include "nav_bar.html" %}
{% block content %}

<div style = "text-align: center; margin: 10%; padding: 5px; text-decoration: none;">
    <button type="button" class="btn btn-outline-primary waves-effect"><a href="{{ url_for('staff.search_animal') }}" style="text-decoration: none; color: black;">Search Animal</a></button>

    <button type="button" class="btn btn-outline-primary waves-effect"><a href="{{ url_for('staff.view_shows') }}" style="text-decoration: none; color: black;">Assigned Shows</a></button>

</div>


{% endblock content %}

App/templates/staff/view_shows.html
{% import 'bootstrap/wtf.html' as wtf %}

{% extends "layout.html" %}
{% include "search_form.html" %}
{% include "nav_bar.html" %}
{% block content %}

 <h1>
        Assigned Shows
 </h1>
{% include "table_temp.html" %}

{% endblock content %}