App/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import views

App/main/views.py
from flask import render_template, redirect, url_for
from flask_login import current_user

from . import bp


@bp.route('/')
def home_page():
    if current_user.is_authenticated:
        if current_user.user_type == "ADMIN":
            return redirect(url_for('admin.admin'))

        elif current_user.user_type == "STAFF":
            return redirect(url_for('staff.staff'))

        elif current_user.user_type == "VISITOR":
            return redirect(url_for('visitor.visitor'))

    return render_template('main/home_page.html', title='Home')

App/templates/main/home_page.html
{% extends "layout.html" %}


{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{{ url_for('main.home_page') }}">Atlanta Zoo</a>
  </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
        </ul>
    </div>
</nav>


<!--<h1 style = "color: #111; font-family: 'Helvetica Neue', sans-serif; font-size: 200px;
    font-weight: bold; letter-spacing: -1px; line-height: 1; text-align: center;">
        Welcome
</h1>-->

<style>
html {
    background-image: url("https://images.pexels.com/photos/1123765/pexels-photo-1123765.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940");
    background-size: cover;
    width:100%;
    height:100%;
    background-repeat: no-repeat;
}

</style>
{% endblock content %}